FROM ghcr.io/mlflow/mlflow:v2.0.1

WORKDIR /mlflow

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "s3://nyc-taxi-data/mlflow/"]